#!/bin/bash

read -p "Enter starting number:" snum
read -p "Enter ending number:" enum

while [[ $snum -le $enum ]];
do
	echo $snum
	((snum++))
done
echo "This is the Sequence"

#infinite loop

while :; do echo "Welcome to my World...";done
